import type { Product } from "./types";

// Catálogo real de Cumbre. Se carga a mano acá (no hay base de datos ni
// Tiendanube de por medio) — agregar un producto nuevo es agregar un
// objeto a este array con fotos ya copiadas a /public.
export const PRODUCTS: Product[] = [
  {
    id: "anafe-samsung-ctr264",
    slug: "anafe-electrico-vitroceramico-samsung-ctr264",
    name: "Anafe Eléctrico Vitrocerámico Samsung CTR264",
    price: 789999,
    compareAtPrice: 908000,
    images: ["/products/anafe.png"],
    line: "cumbre-home",
    category: "Hornos y Anafes",
    description:
      "Anafe eléctrico vitrocerámico Samsung con 4 zonas de cocción. Fácil limpieza y controles táctiles. 18 cuotas sin interés y envío gratis.",
    stock: 10,
  },
  {
    id: "aire-samsung-ar40f12",
    slug: "aire-acondicionado-samsung-split-ar40f12-12kbtu",
    name: "Aire Acondicionado Samsung Split Frío/Calor AR40F12 12KBTU Inverter",
    price: 1349999,
    compareAtPrice: 1620000,
    images: ["/products/ac1.png"],
    line: "electrodomesticos",
    category: "Aire Acondicionado y Climatización",
    description:
      "Split frío/calor Samsung Inverter 12000 BTU, bajo consumo eléctrico. 18 cuotas sin interés y envío gratis.",
    stock: 8,
  },
  {
    id: "horno-samsung-dual-cook-flex",
    slug: "horno-electrico-samsung-dual-cook-flex-serie-5",
    name: "Horno Eléctrico Samsung Dual Cook Flex Serie 5",
    price: 2269999,
    compareAtPrice: 2837000,
    images: ["/products/horno-dual.png"],
    line: "cumbre-home",
    category: "Hornos y Anafes",
    description:
      "Horno eléctrico empotrable Samsung con tecnología Dual Cook Flex: dos cámaras independientes para cocinar a distintas temperaturas al mismo tiempo. 18 cuotas sin interés y envío gratis.",
    stock: 5,
  },
  {
    id: "aire-samsung-ar24bsh",
    slug: "aire-acondicionado-samsung-split-ar24bsh",
    name: "Aire Acondicionado Samsung Split Frío/Calor AR24BSH con ahorro energético",
    price: 2999999,
    compareAtPrice: 3900000,
    images: ["/products/ac2.png"],
    line: "electrodomesticos",
    category: "Aire Acondicionado y Climatización",
    description:
      "Split frío/calor Samsung con ahorro energético. 18 cuotas sin interés.",
    stock: 6,
  },
  {
    id: "microondas-samsung-smart-32",
    slug: "horno-microondas-samsung-smart-32-litros-air-fry",
    name: "Horno Microondas Samsung Smart 32 lts Air Fry Convección Negro",
    price: 769999,
    compareAtPrice: 885000,
    images: ["/products/microondas.png"],
    line: "cumbre-home",
    category: "Microondas",
    description:
      "Microondas Samsung Smart de 32 litros con función Air Fry y convección — cocina, gratina y fríe con aire. 6 cuotas sin interés y envío gratis.",
    stock: 12,
  },
  {
    id: "tv-samsung-55-crystal-uhd",
    slug: "smart-tv-samsung-55-crystal-uhd-4k",
    name: 'Smart TV Samsung 55" Crystal UHD 4K',
    price: 1099999,
    compareAtPrice: 1320000,
    images: ["/products/tv1.png"],
    line: "electrodomesticos",
    category: "TV y Audio",
    description:
      'Smart TV Samsung 55" Crystal UHD 4K. 9 cuotas sin interés y envío gratis.',
    stock: 7,
  },
  {
    id: "tv-samsung-50-u8000f",
    slug: "televisor-samsung-50-crystal-uhd-u8000f-2025",
    name: 'Televisor Samsung 50" Crystal UHD U8000F 4K Smart TV 2025',
    price: 917999,
    compareAtPrice: 1147000,
    images: ["/products/tv2.png"],
    line: "electrodomesticos",
    category: "TV y Audio",
    description:
      'Televisor Samsung 50" Crystal UHD U8000F, modelo 2025. 6 cuotas sin interés y envío gratis.',
    stock: 7,
  },
  {
    id: "tv-tcl-55-v6c",
    slug: "televisor-tcl-55-v6c-4k-hdr-google-tv",
    name: 'Televisor TCL 55" V6C 4K HDR Google TV',
    price: 1114999,
    compareAtPrice: 1449000,
    images: ["/products/tv3.png"],
    line: "electrodomesticos",
    category: "TV y Audio",
    description:
      'Televisor TCL 55" 4K HDR con Google TV integrado. 18 cuotas sin interés y envío gratis.',
    stock: 6,
  },
  {
    id: "tv-samsung-55-u8000f",
    slug: "televisor-samsung-55-crystal-uhd-u8000f-2025",
    name: 'Televisor Samsung 55" Crystal UHD U8000F 4K Smart TV 2025',
    price: 1039999,
    compareAtPrice: 1196000,
    images: ["/products/tv4.png"],
    line: "electrodomesticos",
    category: "TV y Audio",
    description:
      'Televisor Samsung 55" Crystal UHD U8000F, modelo 2025. 6 cuotas sin interés y envío gratis.',
    stock: 5,
  },
  {
    id: "tv-samsung-43-neo-qled",
    slug: "televisor-samsung-43-neo-qled-4k-qn90d",
    name: 'Televisor Samsung 43" Neo QLED 4K QN90D',
    price: 1999999,
    compareAtPrice: 2400000,
    images: ["/products/tv5.png"],
    line: "electrodomesticos",
    category: "TV y Audio",
    description:
      'Televisor Samsung 43" Neo QLED 4K, serie QN90D. 9 cuotas sin interés y envío gratis.',
    stock: 4,
  },
  {
    id: "heladera-samsung-side-by-side-rs27t5561b1",
    slug: "heladera-samsung-side-by-side-rs27t5561b1-685l",
    name: "Heladera Samsung Side by Side RS27T5561B1/ED de 685L",
    price: 4809999,
    compareAtPrice: 6012000,
    images: ["/products/heladera1.png"],
    line: "electrodomesticos",
    category: "Heladeras y Freezers",
    description:
      "Heladera Samsung Side by Side de 685 litros, con dispenser de agua/hielo y Family Hub. 9 cuotas sin interés.",
    stock: 3,
  },
  {
    id: "lavasecarropas-samsung-bespoke-ai",
    slug: "lavasecarropas-samsung-bespoke-ai-22kg-15kg",
    name: "Lavasecarropas Samsung Bespoke AI de 22Kg de lavado y 15Kg de secado",
    price: 5999999,
    compareAtPrice: 7800000,
    images: ["/products/lavasec1.png"],
    line: "electrodomesticos",
    category: "Lavado y Secado",
    description:
      "Lavasecarropas Samsung Bespoke AI, 22kg de lavado y 15kg de secado. 18 cuotas sin interés y envío gratis.",
    stock: 3,
  },
  {
    id: "heladera-samsung-french-door-836l",
    slug: "heladera-samsung-french-door-view-836l-inverter",
    name: "Heladera Samsung French Door View 836L Inverter WiFi Silver",
    price: 4799999,
    compareAtPrice: 5520000,
    images: ["/products/heladera2.png"],
    line: "electrodomesticos",
    category: "Heladeras y Freezers",
    description:
      "Heladera Samsung French Door de 836 litros, Inverter, conectividad WiFi. 9 cuotas sin interés.",
    stock: 3,
  },
  {
    id: "lavasecarropas-samsung-wd4000t",
    slug: "lavasecarropas-samsung-9-5kg-ecobubble-wd4000t",
    name: "Lavasecarropas Samsung 9,5kg con Ecobubble WD4000T Blanco",
    price: 2999999,
    compareAtPrice: 3600000,
    images: ["/products/lavasec2.png"],
    line: "electrodomesticos",
    category: "Lavado y Secado",
    description:
      "Lavasecarropas Samsung 9,5kg con tecnología Ecobubble. 18 cuotas sin interés y envío gratis.",
    stock: 5,
  },
  {
    id: "heladera-samsung-french-door-431l",
    slug: "heladera-samsung-french-door-431l-twin-cooling-inox",
    name: "Heladera Samsung French Door 431L Twin Cooling Acero Inox",
    price: 2849999,
    compareAtPrice: 3562000,
    images: ["/products/heladera3.png"],
    line: "electrodomesticos",
    category: "Heladeras y Freezers",
    description:
      "Heladera Samsung French Door de 431 litros con tecnología Twin Cooling. 9 cuotas sin interés.",
    stock: 4,
  },
  {
    id: "heladera-samsung-bespoke-328-white",
    slug: "heladera-samsung-bespoke-328lts-clean-white",
    name: "Heladera Samsung Bespoke 328Lts Clean White",
    price: 2549999,
    compareAtPrice: 3315000,
    images: ["/products/heladera4.png"],
    line: "electrodomesticos",
    category: "Heladeras y Freezers",
    description:
      "Heladera Samsung Bespoke de 328 litros, color blanco. Diseño minimalista.",
    stock: 4,
  },
  {
    id: "heladera-samsung-bespoke-328-gray",
    slug: "heladera-samsung-bespoke-328-lts-rb33-satin-gray",
    name: "Heladera Samsung Bespoke 328 lts RB33 Satin Gray",
    price: 2549999,
    compareAtPrice: 2932000,
    images: ["/products/heladera5.png"],
    line: "electrodomesticos",
    category: "Heladeras y Freezers",
    description:
      "Heladera Samsung Bespoke de 328 litros, color gris satinado.",
    stock: 4,
  },
  {
    id: "lavarropas-samsung-9-5kg-ecobubble",
    slug: "lavarropas-samsung-blanco-9-5kg-inverter-ecobubble",
    name: "Lavarropas Samsung Blanco 9.5Kg Inverter con Ecobubble",
    price: 2499999,
    compareAtPrice: 3000000,
    images: ["/products/lavarropas3.png"],
    line: "electrodomesticos",
    category: "Lavado y Secado",
    description:
      "Lavarropas Samsung Inverter de 9,5kg con tecnología Ecobubble. 18 cuotas sin interés y envío gratis.",
    stock: 6,
  },
  {
    id: "heladera-tcl-428l-cross-door",
    slug: "heladera-tcl-428l-cross-door-no-frost-inverter-p460cd",
    name: "Heladera TCL 428L Cross Door No Frost Inverter Inox P460CD",
    price: 2289999,
    compareAtPrice: 2862000,
    images: ["/products/heladera6.png"],
    line: "electrodomesticos",
    category: "Heladeras y Freezers",
    description:
      "Heladera TCL Cross Door de 428 litros, No Frost Inverter. 18 cuotas sin interés.",
    stock: 3,
  },
  {
    id: "heladera-samsung-517l-freezer-superior",
    slug: "heladera-samsung-517l-freezer-superior-ai-energy-mode",
    name: "Heladera Samsung 517L Freezer Superior con AI Energy Mode Black",
    price: 2149999,
    compareAtPrice: 2795000,
    images: ["/products/heladera7.png"],
    line: "electrodomesticos",
    category: "Heladeras y Freezers",
    description:
      "Heladera Samsung 517 litros, freezer superior, con AI Energy Mode para ahorro de energía.",
    stock: 4,
  },
  {
    id: "heladera-samsung-382l-twin-cooling",
    slug: "heladera-samsung-freezer-superior-twin-cooling-plus-382lt",
    name: "Heladera Samsung freezer superior Twin Cooling Plus 382Lt",
    price: 1678999,
    compareAtPrice: 1931000,
    images: ["/products/heladera8.png"],
    line: "electrodomesticos",
    category: "Heladeras y Freezers",
    description:
      "Heladera Samsung 382 litros, freezer superior, tecnología Twin Cooling Plus.",
    stock: 5,
  },
  {
    id: "heladera-samsung-362l-twin-cooling",
    slug: "heladera-samsung-freezer-superior-twin-cooling-plus-362l",
    name: "Heladera Samsung freezer superior Twin Cooling Plus 362 L",
    price: 1554999,
    compareAtPrice: 1866000,
    images: ["/products/heladera9.png"],
    line: "electrodomesticos",
    category: "Heladeras y Freezers",
    description:
      "Heladera Samsung 362 litros, freezer superior, tecnología Twin Cooling Plus.",
    stock: 5,
  },
  {
    id: "lavarropas-samsung-7-5kg-carga-superior",
    slug: "lavarropas-samsung-inverter-7-5kg-carga-superior-ecobubble",
    name: "Lavarropas Samsung Inverter 7,5kg Carga Superior Digital Ecobubble Blanco",
    price: 1499999,
    compareAtPrice: 1875000,
    images: ["/products/lavarropas4.png"],
    line: "electrodomesticos",
    category: "Lavado y Secado",
    description:
      "Lavarropas Samsung Inverter de carga superior, 7,5kg, con Ecobubble. 18 cuotas sin interés y envío gratis.",
    stock: 6,
  },
  {
    id: "heladera-samsung-321l-twin-cooling",
    slug: "heladera-samsung-freezer-superior-twin-cooling-plus-321lt",
    name: "Heladera Samsung Freezer Superior Twin Cooling Plus 321Lt",
    price: 1289999,
    compareAtPrice: 1677000,
    images: ["/products/heladera10.png"],
    line: "electrodomesticos",
    category: "Heladeras y Freezers",
    description:
      "Heladera Samsung 321 litros, freezer superior, tecnología Twin Cooling Plus.",
    stock: 6,
  },
  {
    id: "freezer-samsung-287l",
    slug: "freezer-horizontal-samsung-287l-inverter-grey",
    name: "Freezer Horizontal Samsung 287L Inverter Grey",
    price: 1009999,
    compareAtPrice: 1161000,
    images: ["/products/freezer1.png"],
    line: "electrodomesticos",
    category: "Heladeras y Freezers",
    description:
      "Freezer horizontal Samsung de 287 litros, tecnología Inverter. 9 cuotas sin interés.",
    stock: 5,
  },
  {
    id: "freezer-samsung-198l",
    slug: "freezer-horizontal-samsung-198l-inverter-grey",
    name: "Freezer Horizontal Samsung 198L Inverter Grey",
    price: 839999,
    compareAtPrice: 1008000,
    images: ["/products/freezer2.png"],
    line: "electrodomesticos",
    category: "Heladeras y Freezers",
    description:
      "Freezer horizontal Samsung de 198 litros, tecnología Inverter. 9 cuotas sin interés.",
    stock: 5,
  },
  {
    id: "microondas-samsung-22l-negro",
    slug: "microondas-samsung-22l-850w-grill-1100w-negro",
    name: "Microondas Samsung 22L 850W/Grill 1100W Negro",
    price: 744999,
    compareAtPrice: 931000,
    images: ["/products/micro1.png"],
    line: "cumbre-home",
    category: "Microondas",
    description:
      "Microondas Samsung de 22 litros con grill, 850W/1100W. 6 cuotas sin interés y envío gratis.",
    stock: 8,
  },
  {
    id: "microondas-samsung-22l-inox",
    slug: "microondas-samsung-22l-850w-grill-1100w-inox",
    name: "Microondas Samsung 22L 850W/Grill 1100W Inox",
    price: 744999,
    compareAtPrice: 968000,
    images: ["/products/micro2.png"],
    line: "cumbre-home",
    category: "Microondas",
    description:
      "Microondas Samsung de 22 litros con grill, 850W/1100W, acabado inox. 9 cuotas sin interés y envío gratis.",
    stock: 8,
  },
  {
    id: "campana-samsung-60cm",
    slug: "campana-samsung-filtro-lavable-led-60cm",
    name: "Campana Samsung con filtro lavable de aluminio, luces LED y control táctil de 60cm",
    price: 759999,
    compareAtPrice: 874000,
    images: ["/products/campana1.png"],
    line: "cumbre-home",
    category: "Campanas y Extractores",
    description:
      "Campana extractora Samsung de 60cm, filtro lavable de aluminio, luces LED y control táctil. 12 cuotas sin interés y envío gratis.",
    stock: 4,
  },
  {
    id: "lavarropas-tcl-p606fl",
    slug: "lavarropas-tcl-p606fl-carga-frontal-6kg-inverter",
    name: "Lavarropas TCL P606FL Carga Frontal 6kg Inverter Gris",
    price: 694999,
    compareAtPrice: 834000,
    images: ["/products/lavarropas5.png"],
    line: "electrodomesticos",
    category: "Lavado y Secado",
    description:
      "Lavarropas TCL de carga frontal, 6kg, tecnología Inverter.",
    stock: 6,
  },
  {
    id: "microondas-samsung-bespoke-gris",
    slug: "microondas-samsung-bespoke-grill-fry-30l-gris",
    name: "Microondas Samsung Bespoke con Grill Fry 30L Gris",
    price: 673999,
    compareAtPrice: 842000,
    images: ["/products/micro3.png"],
    line: "cumbre-home",
    category: "Microondas",
    description:
      "Microondas Samsung Bespoke con función Grill Fry, 30 litros, color gris. Envío gratis.",
    stock: 6,
  },
  {
    id: "microondas-samsung-bespoke-blanco",
    slug: "microondas-samsung-bespoke-grill-fry-30l-blanco",
    name: "Microondas Samsung Bespoke con Grill Fry 30L Blanco",
    price: 673999,
    compareAtPrice: 876000,
    images: ["/products/micro4.png"],
    line: "cumbre-home",
    category: "Microondas",
    description:
      "Microondas Samsung Bespoke con función Grill Fry, 30 litros, color blanco. Envío gratis.",
    stock: 6,
  },
  {
    id: "anafe-longvie-multigas-4",
    slug: "anafe-a-gas-longvie-multigas-4-hornallas-blanco",
    name: "Anafe a gas Longvie Multigas 4 hornallas Blanco",
    price: 779999,
    compareAtPrice: 897000,
    images: ["/products/anafe2.png"],
    line: "cumbre-home",
    category: "Hornos y Anafes",
    description:
      "Anafe a gas Longvie Multigas de 4 hornallas, color blanco. 18 cuotas sin interés y envío gratis.",
    stock: 5,
  },
  {
    id: "microondas-samsung-bespoke-32l",
    slug: "microondas-samsung-bespoke-mg32dg4524atbg-grill-32lt",
    name: "Microondas Samsung Bespoke MG32DG4524ATBG Grill 32lt Silver",
    price: 629999,
    compareAtPrice: 756000,
    images: ["/products/micro5.png"],
    line: "cumbre-home",
    category: "Microondas",
    description:
      "Microondas Samsung Bespoke con grill, 32 litros, color silver. Envío gratis.",
    stock: 5,
  },
  {
    id: "anafe-samsung-gas-4h-acero",
    slug: "anafe-a-gas-samsung-empotrable-4-hornallas-60cm-acero",
    name: "Anafe a Gas Samsung Empotrable 4 Hornallas 60 cm Acero",
    price: 629999,
    compareAtPrice: 787000,
    images: ["/products/anafe3.png"],
    line: "cumbre-home",
    category: "Hornos y Anafes",
    description:
      "Anafe a gas Samsung empotrable, 4 hornallas, 60cm, acabado acero. 9 cuotas sin interés y envío gratis.",
    stock: 5,
  },
  {
    id: "anafe-samsung-gas-4h-negro",
    slug: "anafe-a-gas-samsung-empotrable-4-hornallas-60cm-negro",
    name: "Anafe a Gas Samsung Empotrable 4 Hornallas 60 cm Negro",
    price: 649999,
    compareAtPrice: 845000,
    images: ["/products/anafe4.png"],
    line: "cumbre-home",
    category: "Hornos y Anafes",
    description:
      "Anafe a gas Samsung empotrable, 4 hornallas, 60cm, acabado negro. 9 cuotas sin interés y envío gratis.",
    stock: 5,
  },
  {
    id: "anafe-longvie-a2600bf",
    slug: "anafe-multigas-longvie-a2600bf-blanco",
    name: "Anafe Multigas Longvie A2600BF Blanco",
    price: 556499,
    compareAtPrice: 640000,
    images: ["/products/anafe5.png"],
    line: "cumbre-home",
    category: "Hornos y Anafes",
    description:
      "Anafe multigas Longvie A2600BF, color blanco. 18 cuotas sin interés y envío gratis.",
    stock: 5,
  },
  {
    id: "anafe-samsung-ctr432",
    slug: "anafe-electrico-vitroceramico-samsung-ctr432",
    name: "Anafe Eléctrico Vitrocerámico Samsung CTR432",
    price: 409999,
    compareAtPrice: 492000,
    images: ["/products/anafe6.png"],
    line: "cumbre-home",
    category: "Hornos y Anafes",
    description:
      "Anafe eléctrico vitrocerámico Samsung, 2 zonas de cocción. 9 cuotas sin interés y envío gratis.",
    stock: 6,
  },
];

export function getProductsByLine(line: Product["line"]) {
  return PRODUCTS.filter((p) => p.line === line);
}

export function getProductBySlug(slug: string) {
  return PRODUCTS.find((p) => p.slug === slug);
}
